### ISSUE TITLE
install_requires

### ISSUE THREAD

**Issue by accesstokens** [junhoyeo/threads-py#21]
i believe the install also requires langchain, as when i installed threads-py in venv it said langchain not found, but worked once installed seperatly. Might want to add langchain to install_requires in setup.py. other than that nice work on the package bro!

**Comment by abdhan** [comment]
Can confirm that is the case. But seems to be already included in requirements.txt

**Comment by junhoyeo** [comment]
👍👍 nice point

**Comment by junhoyeo** [comment]
@accesstokens @abdhan Hey guys! From [v0.0.8](https://github.com/junhoyeo/threads-py/releases/tag/v0.0.8], we are now using Poetry, and we moved deps for `threadspy.ai` to [a group](https://python-poetry.org/docs/managing-dependencies/#installing-group-dependencies).

- If you run `pip install --no-cache-dir --upgrade threads-py`, you'll be able to install `threads-py` with only the minimal deps needed for the core `ThreadsAPI` class
- For now, if you want to install deps for `ai` you can simply run `poetry install --with ai` in the project folder.
- Gonna change our config to `extras` for `pip` support soon...
  - https://stackoverflow.com/questions/71405744/whats-the-difference-between-extras-and-groups-in-poetry
