### ISSUE TITLE
Where can I find the v0.0.7?

### ISSUE THREAD

**Issue by moosl** [junhoyeo/threads-py#22]
it seems the latest release version is 0.0.6.

**Comment by junhoyeo** [comment]
Can we draft a new release? @Mineru98
Will be helpful if you can add my PyPI account as an collaborator so I can release `threads-py` modules when ur absent 😉

**Comment by Mineru98** [comment]
I haven't finished testing all the features we've added yet, so we haven't released them.

**Comment by Mineru98** [comment]
@junhoyeo Tell me your PyPI username

**Comment by junhoyeo** [comment]
> I haven't finished testing all the features we've added yet, so we haven't released them.

I see, thanks!

> @junhoyeo Tell me your PyPI username

@Mineru98 it's `junhoyeo` 🙌

**Comment by junhoyeo** [comment]
Hi, @moosl! We just released [v0.0.8](https://github.com/junhoyeo/threads-py/releases/tag/v0.0.8). 🎉 
You can install the latest version with the following:

```
pip3 install --no-cache-dir --upgrade threads-py
```
