### ISSUE TITLE
Retrieve post_id from post_url

### ISSUE THREAD

**Issue by RedcodesDev** [junhoyeo/threads-py#7]
On the README.md it states that there is support for retrieving the post_id from the post_url, but I can't find any documentation or method for it in this repo.

**Comment by Mineru98** [comment]
> On the README.md it states that there is support for retrieving the post_id from the post_url, but I can't find any documentation or method for it in this repo.

The PostID for that thread is `3140957200974444958`. We are looking up the thread data from that.

It would be handy to have the ability to parse the PostID from the URL as you say, so I'll close this issue when we add that feature.

**Comment by Mineru98** [comment]
@RedcodesDev We've finished patching this issue.
